### ISSUE TITLE
Test report in html format

### ISSUE THREAD

**Issue by anandsunderraman** [comtihon/catcher_modules#10]
unable to make out from docs if there is an option to generate a test report.

Willing to contribute if there is an opportunity to do so

**Comment by comtihon** [comment]
Hi, 
Right now catcher doesn't have any reports, but I think it would be nice to have.
What do you expect to see in this html report?
If you are willing to contribute I'd be very happy.

**Comment by anandsunderraman** [comment]
I was hoping to see each step listed and the output of each step to make it easy do troubleshoot and integrate with CI /CD pipeline

**Comment by comtihon** [comment]
html report was implemented in https://github.com/comtihon/catcher/pull/239
